Add root uid detection

diff --git a/bin/update-brew b/bin/update-brew
--- a/bin/update-brew
+++ b/bin/update-brew
@@ -35,69 +35,71 @@ set -euf
 #     git reset --hard origin/master
 #     brew update --force
 #
-if command -v brew >/dev/null 2>&1; then
-    # Brew strongly prefers to run as the current user.
-    # Otherwise, brew tends to carp due to ownership issues.
-    this_uid="$(id -u "$(whoami)")"
-    brew_uid="$(stat -f %u "$(brew --cellar)")"
-    if [ "$this_uid" -eq "$brew_uid" ]; then
-    
-        arg_verbose=""; if [ -n "${VERBOSE+1}" ] && [ "$VERBOSE" = true ]; then arg_verbose="--verbose"; fi
-        arg_debug=""; if [ -n "${DEBUG+1}" ] && [ "$DEBUG" = true ]; then arg_debug="--debug"; fi
+if [ "$(id -u)" -ne 0 ]; then
+    if command -v brew >/dev/null 2>&1; then
+        # Brew strongly prefers to run as the current user.
+        # Otherwise, brew tends to carp due to ownership issues.
+        this_uid="$(id -u "$(whoami)")"
+        brew_uid="$(stat -f %u "$(brew --cellar)")"
+        if [ "$this_uid" -eq "$brew_uid" ]; then
+        
+            arg_verbose=""; if [ -n "${VERBOSE+1}" ] && [ "$VERBOSE" = true ]; then arg_verbose="--verbose"; fi
+            arg_debug=""; if [ -n "${DEBUG+1}" ] && [ "$DEBUG" = true ]; then arg_debug="--debug"; fi
 
-        # Cleanup in order to make space and mitigate stale formulas
-        brew cleanup $arg_verbose $arg_debug
+            # Cleanup in order to make space and mitigate stale formulas
+            brew cleanup $arg_verbose $arg_debug
 
-        # Update the brew taps one by one via git
-        for tap in $(brew tap); do
-            repo=$(brew --repo "$tap")
-            cd "$repo"
-            git clean -dfx
-            origin=$(git remote -v | grep -m1 '(fetch)' | awk '{print $1}')
-            branch=$(git branch --show-current)
-            git reset --hard "$origin/$branch"
-            git pull "$origin" "$branch"
-        done
+            # Update the brew taps one by one via git
+            for tap in $(brew tap); do
+                repo=$(brew --repo "$tap")
+                cd "$repo"
+                git clean -dfx
+                origin=$(git remote -v | grep -m1 '(fetch)' | awk '{print $1}')
+                branch=$(git branch --show-current)
+                git reset --hard "$origin/$branch"
+                git pull "$origin" "$branch"
+            done
 
-        # Update the brew knowledgebase via the typical command.
-        brew update $arg_verbose $arg_debug
+            # Update the brew knowledgebase via the typical command.
+            brew update $arg_verbose $arg_debug
 
-        # As of 2019-04-10, these loops below are the best known simple
-        # way to figure out which items are stil outdated, then upgrade
-        # each one, one by one, and continuing even if any item fails.
+            # As of 2019-04-10, these loops below are the best known simple
+            # way to figure out which items are stil outdated, then upgrade
+            # each one, one by one, and continuing even if any item fails.
 
-        brew outdated | 
-        while read -r x; do
-            brew reinstall $arg_verbose $arg_debug --force "$x" || true
-        done
+            brew outdated | 
+            while read -r x; do
+                brew reinstall $arg_verbose $arg_debug --force "$x" || true
+            done
 
-        brew outdated --cask | 
-        while read -r x; do
-            brew reinstall $arg_verbose $arg_debug --force "$x" || true
-        done
+            brew outdated --cask | 
+            while read -r x; do
+                brew reinstall $arg_verbose $arg_debug --force "$x" || true
+            done
 
-        brew outdated --cask --greedy --verbose |
-        grep -v '(latest)' |
-        awk '{print $1}' |
-        while read -r x; do
-            brew reinstall $arg_verbose $arg_debug --force "$x" || true
-        done
+            brew outdated --cask --greedy --verbose |
+            grep -v '(latest)' |
+            awk '{print $1}' |
+            while read -r x; do
+                brew reinstall $arg_verbose $arg_debug --force "$x" || true
+            done
 
-        # Upgrade all the normal applications.
-        brew upgrade $arg_verbose $arg_debug
-        brew cleanup $arg_verbose $arg_debug
+            # Upgrade all the normal applications.
+            brew upgrade $arg_verbose $arg_debug
+            brew cleanup $arg_verbose $arg_debug
 
-        # Upgrade all the normal applications, plus use greedy flag.
-        brew upgrade $arg_verbose $arg_debug --greedy
-        brew cleanup $arg_verbose $arg_debug
+            # Upgrade all the normal applications, plus use greedy flag.
+            brew upgrade $arg_verbose $arg_debug --greedy
+            brew cleanup $arg_verbose $arg_debug
 
-        # Upgrade all the cask applications.
-        brew upgrade $arg_verbose $arg_debug --cask
-        brew cleanup $arg_verbose $arg_debug
+            # Upgrade all the cask applications.
+            brew upgrade $arg_verbose $arg_debug --cask
+            brew cleanup $arg_verbose $arg_debug
 
-        # Upgrade all the cask applications, plus use greedy flag.
-        brew upgrade $arg_verbose $arg_debug --cask --greedy
-        brew cleanup $arg_verbose $arg_debug
+            # Upgrade all the cask applications, plus use greedy flag.
+            brew upgrade $arg_verbose $arg_debug --cask --greedy
+            brew cleanup $arg_verbose $arg_debug
 
+        fi
     fi
 fi
